# Generated by Django 4.0.3 on 2022-03-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_todo_completed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='picture',
            field=models.FileField(blank=True, default='images/default.jpg', null=True, upload_to='images/'),
        ),
    ]
