# Generated by Django 4.0.3 on 2022-03-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_todo_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='picture',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/'),
        ),
    ]
